name: PMD_Check
run-name: Se ejecuta análisis PMD para ${{ github.actor }} 
on:
  push:
    branches:
      - '*'
    # paths:
    #   - '**.cls'
jobs:
  PMD_Check:
    runs-on: ubuntu-latest
    steps:

      - name: Run Chackout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./dependencies.json
      
      - name: Instalar Herramientas (Salesforce CLI, Salesforce Code Analyzer, Vlocity Build)
        run: |
          npm install --global @salesforce/cli
          sfdx plugins:install @salesforce/sfdx-scanner
          npm install --globally vlocity 
      
      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin' # See 'Supported distributions' for available options
      #     java-version: '17'
      
      - name: Se ejecuta análisis PMD
        run:  |
          mkdir -p ./tmp 
          files=$(git diff --name-only --diff-filter=AMR main -- actions ./Salesforce/main/default/classes/*.cls)
          lstFiles=""
          for file in $files; do
            if [ -z "$lstFiles" ];
            then
              lstFiles="${file}"
            else
              lstFiles="${lstFiles},${file}"
            fi
          done
          sfdx scanner:run --target $lstFiles -f table -e pmd --pmdconfig Ruleset-v1.xml