name: PMD_Check
run-name: Se ejecuta análisis PMD para ${{ github.actor }} 
on:
  push:
    branches:
      - '*'
    # paths:
    #   - '**.cls'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Instalar Herramientas (Salesforce CLI, Salesforce Code Analyzer, Vlocity Build)
        run: |
          npm install @salesforce/cli --global
          sfdx plugins:install @salesforce/sfdx-scanner
          npm install --global vlocity

      - name: Se ejecuta análisis PMD
        uses: actions/checkout@v3
      - run:  sfdx scanner:run --target ".\Salesforce\main\default\classes\" -f "table" -e "pmd" --pmdconfig "Ruleset-v1.xml"